config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :stories do
        collection do
          get :public_list
        end
        member do
          post :inspired
        end
        resources :comments
      end
      post 'auth/login', to: 'authentication#authenticate'
      post 'signup', to: 'users#create'
    end
  end

  namespace :admin do
    resources :categories
    resources :tags
    resources :users

    root to: "users#index"
  end

  namespace :dashboard, path: '/ud' do
    resources :inspirations, only: [:index, :create, :destroy]
    resources :messages
    resources :comments
    resources :brands
    resources :categories do
      match 'preferences', :on => :collection, via: [:get, :post]
    end
    resources :reviews, only: [:index, :create]
    resources :stories, only: [:index, :create]
    resource :profile do
      member do
        put :update_password
      end
    end
  end

  get '/dashboard', to: 'dashboard#index', as: :dashboard

  devise_for :users, controllers: { sessions:           'users/sessions',
                                    registrations:      'users/registrations',
                                    passwords:          'users/passwords',
                                    omniauth_callbacks: 'users/omniauth'
                   }
  resources :users, only: [:show] do
    collection do
      post :varify_handle
    end
  end
  resources :stories, only: [:show]
  get ':handle', to: 'users#home', as: :user_profile
  root to: 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    fetch_stories
  end

  private

  def fetch_stories
    @stories = Story.order("created_at desc").page(params[:page]).per_page(10)
  end
end

app/views/home/_guest_index.html.erb
<div class="container" style="margin-top: 5px">
  <div class="row">
    <div class="col-md-3">
      <%= render "user_area_left", user: User.new %>
    </div>
    <div class="col-md-6 no-side-padding" style="margin-left: -5px;margin-right: -5px;">
      <%= render "stories_section" %>
    </div>
    <div class="col-md-3">
      <%= render "user_area_right" %>
    </div>
  </div>
</div>

app/views/home/_stories_section.html.erb
<div id="stories_container">
  <%= render partial: "home/story", collection: @stories %>
</div>

<div id="infinite-scrolling">
  <%= will_paginate @stories%>
</div>

<script type="text/javascript" charset="utf-8">
    (function() {
        jQuery(function() {
            if ($('#infinite-scrolling').size() > 0) {
                $(window).on('scroll', function() {
                    var more_posts_url;
                    more_posts_url = $('.pagination a[rel=next]').attr('href');
                    if (more_posts_url && $(window).scrollTop() > $(document).height() - $(window).height() - 60) {
                        $('.pagination').html($('.loading_section').html());
                        $.getScript(more_posts_url);
                    }
                });
            }
            $(window).scroll();
        });

    }).call(this);
</script>

app/views/home/_stories_section_react.html.erb
<%= react_component("users/UserStoryList", { user_id: @user&.id, current_user: serialized_current_user }) %>

app/views/home/_story.html.erb
<div class="story-item story-item-popup UserSmallListItem account-summary" data-story-path="<%= story_path(story) %>">
  <div class="content">
    <% if story.brand_id %>
        <%= render "stories/story_brand_head", brand: story.brand %>
    <% else %>
        <%= render "stories/story_user_head", user: story.user %>
    <% end %>
    <p class="story-content">
      <%= story.description %>
    </p>
  </div>
</div>

app/views/home/_user_area_left.html.erb
<div class="user-area user-area-left">
  <div class="DashboardProfileCard  module">
    <%= link_to user_profile_link(user), class: "DashboardProfileCard-bg u-bgUserColor u-block" do %>
        <%= image_tag user_cover_photo(user, :thumb), class: '' %>
    <% end %>

    <div class="DashboardProfileCard-content">
      <%= link_to user_profile_link(user), class: "DashboardProfileCard-avatarLink u-inlineBlock", title: user.name do %>
          <%= image_tag user_avatar_image(user, :thumb), class: 'DashboardProfileCard-avatarImage js-action-profile-avatar' %>
      <% end %>

      <div class="DashboardProfileCard-userFields account-group">
        <div class="DashboardProfileCard-name u-textTruncate">
          <%= link_to user.name, user_profile_link(user), class: "u-textInheritColor js-nav", title: user.name %>
          <span class="UserBadges"></span>
        </div>
        <span class="DashboardProfileCard-screenname u-inlineBlock u-dir" dir="ltr">
          <%= link_to user_profile_link(user), class: "DashboardProfileCard-screennameLink u-linkComplex u-linkClean js-nav", title: user.name do %>
            <span class="username u-dir" dir="ltr">@<b class="u-linkComplex-target"><%= user.handle %></b></span>
          <% end %>
        </span>
      </div>

      <div class="row text-center user-stats margin-top-15">
        <div class="col-md-4">
          <div>
            <strong>Stories</strong>
          </div>
          <span><%= user.stories_count %></span>
        </div>
        <div class="col-md-4">
          <div><strong>Inspired</strong>
          </div>
          <span><%= user.inspirations_count %></span>
        </div>
        <div class="col-md-4">
          <div><strong title="Inspiration Point">IP</strong>
          </div>
          <span><%= user.net_inspiration_point %></span>
        </div>

      </div>
      <div id="user-area-profile-prompt"></div>

    </div>
  </div>


  <div class="module Trends trends">
    <div class="trends-inner">
      <div class="flex-module trends-container context-trends-container">
        <div class="flex-module-header">

          <h5><span class="trend-location js-trend-location">Preferred Categories</span> 
          <%= link_to "(Change)", preferences_dashboard_categories_path, remote: true , class: 'common-popup' %>
          </h5>


        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/_user_area_right.html.erb
<div class="user-area user-area-right">
  <div class="module wtf-module js-wtf-module roaming-module has-content">
    <div class="Footer module roaming-module">
      <div class="flex-module">
        <div class="flex-module-inner">
          <ul class="u-cf">
            <li class="Footer-item Footer-copyright copyright">© <%= Time.now.year %> Inspiring Bangladesh</li>
            <li class="Footer-item"><a class="Footer-link" href="/about" rel="noopener">About</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/_user_index.html.erb
<div class="container" style="margin-top: 5px">
  <div class="row">
    <div class="col-md-3">
      <%= render "user_area_left", user: current_user %>
    </div>
    <div class="col-md-6 no-side-padding" style="margin-left: -5px;margin-right: -5px;">
      <%#= render "home/story_form_popup" if current_user %>
      <%= render "stories_section_react" %>
    </div>
    <div class="col-md-3">
      <%= render "user_area_right" %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<%= render current_user ? "user_index" : "guest_index" %>

app/views/home/index.js.erb
$('#stories_container').append('<%= j render(partial: "home/story", collection: @stories) %>');
<% if @stories.next_page %>
$('.pagination').replaceWith('<%= j will_paginate @stories %>');
<% else %>
$(window).off('scroll');
$('.pagination').remove();
<% end %>

app/views/home/user_index.html.erb
<div class="container" style="margin-top: 5px">
  <div class="row">
    <div class="col-md-3">
      <%= render "user_area_left" %>
    </div>
    <div class="col-md-6 no-side-padding" style="margin-left: -5px;margin-right: -5px;">
      <%= render "user_area_main" %>
    </div>
    <div class="col-md-3">
      <%= render "user_area_right" %>
    </div>
  </div>
</div>